### ISSUE TITLE
New mods causing other mods to not load

### ISSUE THREAD

**Issue by ardenova** [MANOLOV02/BG3-UTAM#8]
I've tried making a couple new mods and each time they cause the game to not load any mods at all.

Here's a link to one that's causing the issue:
https://drive.google.com/file/d/1m1T_qcuZsP4cshoCJzoPnoEABLritery/view?usp=drive_link

**Comment by MANOLOV02** [comment]
Hi. Can't replicate the issue, it's working fine on my machine.

I have used BG3MM to add it from your zip and no issue (the game worked
fine, one container inside another in the tutorial chest)
I have used UTAM to edit it and try it again. No issue again, working
perfectly
Are you sure this is the one giving you issues?

I know that sometimes it happens when the folder name has certain
combinations (ie.e numbers, etc) but this is not the case

See images below

**Comment by MANOLOV02** [comment]
![1086940_20240709055846_1](https://github.com/MANOLOV02/BG3-UTAM/assets/159626309/efab9930-e1fe-46a2-8740-3d32a2ca4ed2)

**Comment by ardenova** [comment]
Thats odd, its definitely the mod causing it on my end because when i remove it there are no issues.  I'll do more testing when i get the chance.

**Comment by MANOLOV02** [comment]
Can you try to build it with modders multitool (I also did that on my machine) but maybe it’s a localization issue (my system is in Spanish)

**Comment by ardenova** [comment]
it looks like the issue was the name, I was trying to rebuild an older mod I made with the same name and apparently that caused the problem even though I removed the old mod completely.

However I ran into another issue, when changing the name of treasure tables it can cause containers that are inside other containers to disappear in the game even though they are listed in treasuretable.txt.

Heres an example:
https://drive.google.com/file/d/1hRefAjU43zLsB_HoonjE6kjCtymj-44N/view?usp=drive_link

**Comment by MANOLOV02** [comment]
Great you found the issue, probably you removed it but remained in the modsettings.lsx generating conflict. Regarding changing treasure, yes it will not track backwards what was referencing the old name and they will lost link. I was hesitant to allow changing names on stats and treasures because of this but I think the flexibility it provides worth it, we just need to be aware of this and re-link the items to the new treasure table. I will look into your example.

**Comment by ardenova** [comment]
Unfortunately, I'm still having the same problem after re-linking the treasure tables, unless I'm misunderstanding what you meant.
here's the updated mod:
https://drive.google.com/file/d/16r2aH_iL3n1gLMApH3vHTeaJHkGshAvD/view?usp=sharing

Also, when deleting and re-adding treasure tables through the world injection window it can cause the treasure table duplication issue again.

**Comment by MANOLOV02** [comment]
I made a video fixing the mod, it easier than writing it down. 
https://youtu.be/GLkO0cRUI4I
Let me know when you watched so i can remove it from the channel (is not listed anyways).

**Comment by ardenova** [comment]
Okay I understand what i did wrong and was able to fix it, thanks so much for your help!

**Comment by MANOLOV02** [comment]
You are welcome. Closing the issue as done. Open a new one if you encounter another problem
